# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deployment.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import empty_pb2 as empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='deployment.proto',
  package='api',
  syntax='proto3',
  serialized_options=b'Z\014api/protobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x64\x65ployment.proto\x12\x03\x61pi\x1a\x0b\x65mpty.proto\"\xbb\x01\n\nDeployment\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0bownerUserId\x18\x02 \x01(\t\x12&\n\x06status\x18\x04 \x01(\x0e\x32\x16.api.Deployment.Status\x12\x0c\n\x04name\x18\x05 \x01(\t\"V\n\x06Status\x12\x0f\n\x0bSTARTING_UP\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\x11\n\rSHUTTING_DOWN\x10\x03\x12\x0f\n\x0bUNREACHABLE\x10\x04\"2\n\rNewDeployment\x12\x13\n\x0bownerUserId\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\".\n\x1cGetDeploymentsForUserRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\"A\n\x14GetDeploymentRequest\x12\x13\n\x0bownerUserId\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x65ploymentId\x18\x02 \x01(\t\"/\n\x17RemoveDeploymentRequest\x12\x14\n\x0c\x64\x65ploymentId\x18\x01 \x01(\t2\xa0\x02\n\x1b\x44\x65ploymentManagementService\x12M\n\x15GetDeploymentsForUser\x12!.api.GetDeploymentsForUserRequest\x1a\x0f.api.Deployment0\x01\x12\x37\n\x10\x43reateDeployment\x12\x12.api.NewDeployment\x1a\x0f.api.Deployment\x12;\n\rGetDeployment\x12\x19.api.GetDeploymentRequest\x1a\x0f.api.Deployment\x12<\n\x10RemoveDeployment\x12\x1c.api.RemoveDeploymentRequest\x1a\n.api.EmptyB\x0eZ\x0c\x61pi/protobufb\x06proto3'
  ,
  dependencies=[empty__pb2.DESCRIPTOR,])



_DEPLOYMENT_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='api.Deployment.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STARTING_UP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SHUTTING_DOWN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNREACHABLE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=140,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_DEPLOYMENT_STATUS)


_DEPLOYMENT = _descriptor.Descriptor(
  name='Deployment',
  full_name='api.Deployment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='api.Deployment.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ownerUserId', full_name='api.Deployment.ownerUserId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='api.Deployment.status', index=2,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='api.Deployment.name', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DEPLOYMENT_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=226,
)


_NEWDEPLOYMENT = _descriptor.Descriptor(
  name='NewDeployment',
  full_name='api.NewDeployment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ownerUserId', full_name='api.NewDeployment.ownerUserId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='api.NewDeployment.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=278,
)


_GETDEPLOYMENTSFORUSERREQUEST = _descriptor.Descriptor(
  name='GetDeploymentsForUserRequest',
  full_name='api.GetDeploymentsForUserRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='api.GetDeploymentsForUserRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=326,
)


_GETDEPLOYMENTREQUEST = _descriptor.Descriptor(
  name='GetDeploymentRequest',
  full_name='api.GetDeploymentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ownerUserId', full_name='api.GetDeploymentRequest.ownerUserId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deploymentId', full_name='api.GetDeploymentRequest.deploymentId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=328,
  serialized_end=393,
)


_REMOVEDEPLOYMENTREQUEST = _descriptor.Descriptor(
  name='RemoveDeploymentRequest',
  full_name='api.RemoveDeploymentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deploymentId', full_name='api.RemoveDeploymentRequest.deploymentId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=395,
  serialized_end=442,
)

_DEPLOYMENT.fields_by_name['status'].enum_type = _DEPLOYMENT_STATUS
_DEPLOYMENT_STATUS.containing_type = _DEPLOYMENT
DESCRIPTOR.message_types_by_name['Deployment'] = _DEPLOYMENT
DESCRIPTOR.message_types_by_name['NewDeployment'] = _NEWDEPLOYMENT
DESCRIPTOR.message_types_by_name['GetDeploymentsForUserRequest'] = _GETDEPLOYMENTSFORUSERREQUEST
DESCRIPTOR.message_types_by_name['GetDeploymentRequest'] = _GETDEPLOYMENTREQUEST
DESCRIPTOR.message_types_by_name['RemoveDeploymentRequest'] = _REMOVEDEPLOYMENTREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Deployment = _reflection.GeneratedProtocolMessageType('Deployment', (_message.Message,), {
  'DESCRIPTOR' : _DEPLOYMENT,
  '__module__' : 'deployment_pb2'
  # @@protoc_insertion_point(class_scope:api.Deployment)
  })
_sym_db.RegisterMessage(Deployment)

NewDeployment = _reflection.GeneratedProtocolMessageType('NewDeployment', (_message.Message,), {
  'DESCRIPTOR' : _NEWDEPLOYMENT,
  '__module__' : 'deployment_pb2'
  # @@protoc_insertion_point(class_scope:api.NewDeployment)
  })
_sym_db.RegisterMessage(NewDeployment)

GetDeploymentsForUserRequest = _reflection.GeneratedProtocolMessageType('GetDeploymentsForUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDEPLOYMENTSFORUSERREQUEST,
  '__module__' : 'deployment_pb2'
  # @@protoc_insertion_point(class_scope:api.GetDeploymentsForUserRequest)
  })
_sym_db.RegisterMessage(GetDeploymentsForUserRequest)

GetDeploymentRequest = _reflection.GeneratedProtocolMessageType('GetDeploymentRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETDEPLOYMENTREQUEST,
  '__module__' : 'deployment_pb2'
  # @@protoc_insertion_point(class_scope:api.GetDeploymentRequest)
  })
_sym_db.RegisterMessage(GetDeploymentRequest)

RemoveDeploymentRequest = _reflection.GeneratedProtocolMessageType('RemoveDeploymentRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEDEPLOYMENTREQUEST,
  '__module__' : 'deployment_pb2'
  # @@protoc_insertion_point(class_scope:api.RemoveDeploymentRequest)
  })
_sym_db.RegisterMessage(RemoveDeploymentRequest)


DESCRIPTOR._options = None

_DEPLOYMENTMANAGEMENTSERVICE = _descriptor.ServiceDescriptor(
  name='DeploymentManagementService',
  full_name='api.DeploymentManagementService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=445,
  serialized_end=733,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDeploymentsForUser',
    full_name='api.DeploymentManagementService.GetDeploymentsForUser',
    index=0,
    containing_service=None,
    input_type=_GETDEPLOYMENTSFORUSERREQUEST,
    output_type=_DEPLOYMENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CreateDeployment',
    full_name='api.DeploymentManagementService.CreateDeployment',
    index=1,
    containing_service=None,
    input_type=_NEWDEPLOYMENT,
    output_type=_DEPLOYMENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetDeployment',
    full_name='api.DeploymentManagementService.GetDeployment',
    index=2,
    containing_service=None,
    input_type=_GETDEPLOYMENTREQUEST,
    output_type=_DEPLOYMENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveDeployment',
    full_name='api.DeploymentManagementService.RemoveDeployment',
    index=3,
    containing_service=None,
    input_type=_REMOVEDEPLOYMENTREQUEST,
    output_type=empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEPLOYMENTMANAGEMENTSERVICE)

DESCRIPTOR.services_by_name['DeploymentManagementService'] = _DEPLOYMENTMANAGEMENTSERVICE

# @@protoc_insertion_point(module_scope)
